### ISSUE TITLE
Wrong floating style for period Selector

### ISSUE THREAD

**Issue by anhnongdan** [vutranvn/QA#1]
Hi Vu, 

Check lai css nhe, period selector bi truot sang ben phai man hinh.

../plugins/QualityAssurance/stylesheets/style.css
.top_controls .periodSelector {
    float: right !important;
}

See this: https://qa.vnpt.bimax.tv/index.php?module=MultiSites&action=index&date=today&period=day&idSite=1

**Comment by vutranvn** [comment]
OK. Done. @anhnongdan  pull code về lại nha
